### ISSUE TITLE
[BUG] Not possible to have two TyphonDL models in one project

### ISSUE THREAD

**Issue by MarieSaphira** [typhon-project/typhondl#75]
**Describe the bug**

If I have two folders in my Project each containing a TyphonDL model (with main model file, database files and dbtypes.tdl), the script generation does not use the right references. Instead of e.g.
```
xsi:type=\"typhonDL:DB\" name=\"RelationalDatabase\" type=\"//@elements.6\">
```
the reference to a .tdl file in a different folder is used:
```
xsi:type=\"typhonDL:DB\" name=\"RelationalDatabase\">    <type href=\"../TyphonDL/dbTypes.tdl#//@elements.0\"/>
```
This leads to an IndexOutOfBounds Exception [here](https://github.com/typhon-project/typhon-polystore-api/blob/6abfaba6bb02d5f057090a2d19a3888cd362a531/com.clms.typhonapi/src/main/java/com/clms/typhonapi/utils/ServiceRegistry.java#L211)

**Expected behavior**

Either how an error when there is more than one DL model in a project or only use DL resources contained in the same folder.

Reported by @patrickneubauer

**Comment by patrickneubauer** [comment]
This is (also) the case for generated database files (i.e. generated by TyphonDL if the user does not select existing database files).

**Comment by MarieSaphira** [comment]
seems to still happen
